model:
  step:
    perception:
      in_channels: &in-ch 16
      out_channels_per_filter: *in-ch
      filters:
        - IDENTITY
        - SOLVER_X
        - SOLVER_Y
    update_rule:
      in_channels: 48
      hidden_channels: 128
      out_channels: *in-ch
    stochastic_cell_update:
      threshold: 0.5
    living_cell_masking:
      threshold: 0.1

logger:
  name: ca-growth-cell_growth
  path: logs
  level: INFO
  message_format: "%(levelname)s %(asctime)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"