model:
  in-channels: &in-ch 16
  perception:
    out-channels-per-filter: *in-ch
    filters:
      - SOLVER_X
      - SOLVER_Y
  dense:
    in_channels: 48
    out_channels: *in-ch
logger:
  name: ca-growth-model
  path: logs
  level: INFO
  message_format: "%(levelname)s %(asctime)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"