model:
  step:
    perception:
      in_channels: &in-ch 32
      out_channels_per_filter: *in-ch
      filters:
        - IDENTITY
        - SOLVER_Y
        - SOLVER_X
    update_rule:
      in_channels: 96
      hidden_channels: 128
      out_channels: *in-ch
    stochastic_cell_update:
      threshold: 0.5
    living_cell_masking:
      threshold: 0.1

train:
  epochs: 10000
  steps: 16
  lr: 0.0001
  scheduler:
    step_size: 1000
    gamma: 0.1
  metrics:
    reset_every: 600
  preview:
    every: 600

logger:
  name: ca-growth
  path: logs
  level: INFO
  message_format: "%(levelname)s %(asctime)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"